export const gender = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
  { label: 'Not Specified', value: null },
]
export const ethnicity = [
  { label: 'American Indian or Alaskan Native', value: 'american-indian' },
  { label: 'Asian', value: 'asian' },
  { label: 'Black or African American', value: 'black-african-american' },
  { label: 'Hispanic or Latino', value: 'hispanic-latino' },
  { label: 'Naive Hawaiian or Pacific Islander', value: 'pacific-islander' },
  { label: 'White', value: 'white' },
  { label: 'Not Specified', value: null },
]
export const disability = [
  { label: 'Yes', value: true },
  { label: 'No', value: false },
  // { label: 'Mobility', value: 'mobility' },
  // { label: 'Congnition', value: 'cognition' },
  // { label: 'Independent Living', value: 'independent-living' },
  // { label: 'Hearing', value: 'hearing' },
  // { label: 'Vision', value: 'vision' },
  // { label: 'Self-Care', value: 'self-care' },
  // { label: 'None', value: 'none' },
]
export const veteran = [
  { label: 'Yes', value: true },
  { label: 'No', value: false },
]
export const nationality = [
  { label: 'Afghan', value: 'afghan' },
  { label: 'Albanian', value: 'albanian' },
  { label: 'Algerian', value: 'algerian' },
  { label: 'American', value: 'american' },
  { label: 'Andorran', value: 'andorran' },
  { label: 'Angolan', value: 'angolan' },
  { label: 'Antiguans', value: 'antiguans' },
  { label: 'Argentinean', value: 'argentinean' },
  { label: 'Armenian', value: 'armenian' },
  { label: 'Australian', value: 'australian' },
  { label: 'Austrian', value: 'austrian' },
  { label: 'Azerbaijani', value: 'azerbaijani' },
  { label: 'Bahamian', value: 'bahamian' },
  { label: 'Bahraini', value: 'bahraini' },
  { label: 'Bangladeshi', value: 'bangladeshi' },
  { label: 'Barbadian', value: 'barbadian' },
  { label: 'Barbudans', value: 'barbudans' },
  { label: 'Batswana', value: 'batswana' },
  { label: 'Belarusian', value: 'belarusian' },
  { label: 'Belgian', value: 'belgian' },
  { label: 'Belizean', value: 'belizean' },
  { label: 'Beninese', value: 'beninese' },
  { label: 'Bhutanese', value: 'bhutanese' },
  { label: 'Bolivian', value: 'bolivian' },
  { label: 'Bosnian', value: 'bosnian' },
  { label: 'Brazilian', value: 'brazilian' },
  { label: 'British', value: 'british' },
  { label: 'Bruneian', value: 'bruneian' },
  { label: 'Bulgarian', value: 'bulgarian' },
  { label: 'Burkinabe', value: 'burkinabe' },
  { label: 'Burmese', value: 'burmese' },
  { label: 'Burundian', value: 'burundian' },
  { label: 'Cambodian', value: 'cambodian' },
  { label: 'Cameroonian', value: 'cameroonian' },
  { label: 'Canadian', value: 'canadian' },
  { label: 'Cape Verdean', value: 'cape-verdean' },
  { label: 'Central African', value: 'central-african' },
  { label: 'Chadian', value: 'chadian' },
  { label: 'Chilean', value: 'chilean' },
  { label: 'Chinese', value: 'chinese' },
  { label: 'Colombian', value: 'colombian' },
  { label: 'Comoran', value: 'comoran' },
  { label: 'Congolese', value: 'congolese' },
  { label: 'Costa Rican', value: 'costa-rican' },
  { label: 'Croatian', value: 'croatian' },
  { label: 'Cuban', value: 'cuban' },
  { label: 'Cypriot', value: 'cypriot' },
  { label: 'Czech', value: 'czech' },
  { label: 'Danish', value: 'danish' },
  { label: 'Djibouti', value: 'djibouti' },
  { label: 'Dominican', value: 'dominican' },
  { label: 'Dutch', value: 'dutch' },
  { label: 'East Timorese', value: 'east-timorese' },
  { label: 'Ecuadorean', value: 'ecuadorean' },
  { label: 'Egyptian', value: 'egyptian' },
  { label: 'Emirian', value: 'emirian' },
  { label: 'Equatorial Guinean', value: 'equatorial-guinean' },
  { label: 'Eritrean', value: 'eritrean' },
  { label: 'Estonian', value: 'estonian' },
  { label: 'Ethiopian', value: 'ethiopian' },
  { label: 'Fijian', value: 'fijian' },
  { label: 'Filipino', value: 'filipino' },
  { label: 'Finnish', value: 'finnish' },
  { label: 'French', value: 'french' },
  { label: 'Gabonese', value: 'gabonese' },
  { label: 'Gambian', value: 'gambian' },
  { label: 'Georgian', value: 'georgian' },
  { label: 'German', value: 'german' },
  { label: 'Ghanaian', value: 'ghanaian' },
  { label: 'Greek', value: 'greek' },
  { label: 'Grenadian', value: 'grenadian' },
  { label: 'Guatemalan', value: 'guatemalan' },
  { label: 'Guinea-Bissauan', value: 'guinea-bissauan' },
  { label: 'Guinean', value: 'guinean' },
  { label: 'Guyanese', value: 'guyanese' },
  { label: 'Haitian', value: 'haitian' },
  { label: 'Herzegovinian', value: 'herzegovinian' },
  { label: 'Honduran', value: 'honduran' },
  { label: 'Hungarian', value: 'hungarian' },
  { label: 'I-Kiribati', value: 'i-kiribati' },
  { label: 'Icelander', value: 'icelander' },
  { label: 'Indian', value: 'indian' },
  { label: 'Indonesian', value: 'indonesian' },
  { label: 'Iranian', value: 'iranian' },
  { label: 'Iraqi', value: 'iraqi' },
  { label: 'Irish', value: 'irish' },
  { label: 'Israeli', value: 'israeli' },
  { label: 'Italian', value: 'italian' },
  { label: 'Ivorian', value: 'ivorian' },
  { label: 'Jamaican', value: 'jamaican' },
  { label: 'Japanese', value: 'japanese' },
  { label: 'Jordanian', value: 'jordanian' },
  { label: 'Kazakhstani', value: 'kazakhstani' },
  { label: 'Kenyan', value: 'kenyan' },
  { label: 'Kittian and Nevisian', value: 'kittian-and-nevisian' },
  { label: 'Kuwaiti', value: 'kuwaiti' },
  { label: 'Kyrgyz', value: 'kyrgyz' },
  { label: 'Laotian', value: 'laotian' },
  { label: 'Latvian', value: 'latvian' },
  { label: 'Lebanese', value: 'lebanese' },
  { label: 'Liberian', value: 'liberian' },
  { label: 'Libyan', value: 'libyan' },
  { label: 'Liechtensteiner', value: 'liechtensteiner' },
  { label: 'Lithuanian', value: 'lithuanian' },
  { label: 'Luxembourger', value: 'luxembourger' },
  { label: 'Macedonian', value: 'macedonian' },
  { label: 'Malagasy', value: 'malagasy' },
  { label: 'Malawian', value: 'malawian' },
  { label: 'Malaysian', value: 'malaysian' },
  { label: 'Maldivian', value: 'maldivian' },
  { label: 'Malian', value: 'malian' },
  { label: 'Maltese', value: 'maltese' },
  { label: 'Marshallese', value: 'marshallese' },
  { label: 'Mauritanian', value: 'mauritanian' },
  { label: 'Mauritian', value: 'mauritian' },
  { label: 'Mexican', value: 'mexican' },
  { label: 'Micronesian', value: 'micronesian' },
  { label: 'Moldovan', value: 'moldovan' },
  { label: 'Monacan', value: 'monacan' },
  { label: 'Mongolian', value: 'mongolian' },
  { label: 'Moroccan', value: 'moroccan' },
  { label: 'Mosotho', value: 'mosotho' },
  { label: 'Motswana', value: 'motswana' },
  { label: 'Mozambican', value: 'mozambican' },
  { label: 'Namibian', value: 'namibian' },
  { label: 'Nauruan', value: 'nauruan' },
  { label: 'Nepalese', value: 'nepalese' },
  { label: 'New Zealander', value: 'new-zealander' },
  { label: 'Ni-Vanuatu', value: 'ni-vanuatu' },
  { label: 'Nicaraguan', value: 'nicaraguan' },
  { label: 'Nigerian', value: 'nigerian' },
  { label: 'Nigerien', value: 'nigerien' },
  { label: 'North Korean', value: 'north-korean' },
  { label: 'Northern Irish', value: 'northern-irish' },
  { label: 'Norwegian', value: 'norwegian' },
  { label: 'Omani', value: 'omani' },
  { label: 'Pakistani', value: 'pakistani' },
  { label: 'Palauan', value: 'palauan' },
  { label: 'Panamanian', value: 'panamanian' },
  { label: 'Papua New Guinean', value: 'papua-new-guinean' },
  { label: 'Paraguayan', value: 'paraguayan' },
  { label: 'Peruvian', value: 'peruvian' },
  { label: 'Polish', value: 'polish' },
  { label: 'Portuguese', value: 'portuguese' },
  { label: 'Qatari', value: 'qatari' },
  { label: 'Romanian', value: 'romanian' },
  { label: 'Russian', value: 'russian' },
  { label: 'Rwandan', value: 'rwandan' },
  { label: 'Saint Lucian', value: 'saint-lucian' },
  { label: 'Salvadoran', value: 'salvadoran' },
  { label: 'Samoan', value: 'samoan' },
  { label: 'San Marinese', value: 'san-marinese' },
  { label: 'Sao Tomean', value: 'sao-tomean' },
  { label: 'Saudi', value: 'saudi' },
  { label: 'Scottish', value: 'scottish' },
  { label: 'Senegalese', value: 'senegalese' },
  { label: 'Serbian', value: 'serbian' },
  { label: 'Seychellois', value: 'seychellois' },
  { label: 'Sierra Leonean', value: 'sierra-leonean' },
  { label: 'Singaporean', value: 'singaporean' },
  { label: 'Slovakian', value: 'slovakian' },
  { label: 'Slovenian', value: 'slovenian' },
  { label: 'Solomon Islander', value: 'solomon-islander' },
  { label: 'Somali', value: 'somali' },
  { label: 'South African', value: 'south-african' },
  { label: 'South Korean', value: 'south-korean' },
  { label: 'Spanish', value: 'spanish' },
  { label: 'Sri Lankan', value: 'sri-lankan' },
  { label: 'Sudanese', value: 'sudanese' },
  { label: 'Surinamer', value: 'surinamer' },
  { label: 'Swazi', value: 'swazi' },
  { label: 'Swedish', value: 'swedish' },
  { label: 'Swiss', value: 'swiss' },
  { label: 'Syrian', value: 'syrian' },
  { label: 'Taiwanese', value: 'taiwanese' },
  { label: 'Tajik', value: 'tajik' },
  { label: 'Tanzanian', value: 'tanzanian' },
  { label: 'Thai', value: 'thai' },
  { label: 'Togolese', value: 'togolese' },
  { label: 'Tongan', value: 'tongan' },
  { label: 'Trinidadian or Tobagonian', value: 'trinidadian-or-tobagonian' },
  { label: 'Tunisian', value: 'tunisian' },
  { label: 'Turkish', value: 'turkish' },
  { label: 'Tuvaluan', value: 'tuvaluan' },
  { label: 'Ugandan', value: 'ugandan' },
  { label: 'Ukrainian', value: 'ukrainian' },
  { label: 'Uruguayan', value: 'uruguayan' },
  { label: 'Uzbekistani', value: 'uzbekistani' },
  { label: 'Venezuelan', value: 'venezuelan' },
  { label: 'Vietnamese', value: 'vietnamese' },
  { label: 'Welsh', value: 'welsh' },
  { label: 'Yemenite', value: 'yemenite' },
  { label: 'Zambian', value: 'zambian' },
  { label: 'Zimbabwean', value: 'zimbabwean' },
  { label: 'Not Specified', value: null },
]
